name: ✅ Tâche
description: Travail à faire (feature, configuration, design ou contenu)
title: "[TÂCHE] : "
labels: ["tâche"]
assignees: ["hassanetoure2013-hub"]
body:
  - type: dropdown
    id: priorité
    attributes:
      label: Priorité
      options:
        - Haute
        - Moyenne
        - Basse
      default: 1
  - type: textarea
    id: description
    attributes:
      label: Description
      placeholder: Détails, objectifs, critères d’acceptation, liens...
  - type: input
    id: estimation
    attributes:
      label: Estimation (heures)
      placeholder: ex. 3
  - type: checkboxes
    id: étapes
    attributes:
      label: Checklist
      options:
        - label: Dev terminé
        - label: Tests locaux OK
        - label: Revu et validé
        - label: Déployé sur Vercel
